package com.ayz.reggie.pojo;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;

public class AddressBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.id
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.user_id
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.consignee
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.sex
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.phone
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.province_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.province_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.city_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.city_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.district_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.district_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.detail
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.label
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.is_default
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.create_time
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.update_time
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.create_user
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.update_user
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_book.is_deleted
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.id
     *
     * @return the value of address_book.id
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.id
     *
     * @param id the value for address_book.id
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.user_id
     *
     * @return the value of address_book.user_id
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.user_id
     *
     * @param userId the value for address_book.user_id
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.consignee
     *
     * @return the value of address_book.consignee
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.consignee
     *
     * @param consignee the value for address_book.consignee
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.sex
     *
     * @return the value of address_book.sex
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.sex
     *
     * @param sex the value for address_book.sex
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.phone
     *
     * @return the value of address_book.phone
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.phone
     *
     * @param phone the value for address_book.phone
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.province_code
     *
     * @return the value of address_book.province_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.province_code
     *
     * @param provinceCode the value for address_book.province_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.province_name
     *
     * @return the value of address_book.province_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.province_name
     *
     * @param provinceName the value for address_book.province_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.city_code
     *
     * @return the value of address_book.city_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.city_code
     *
     * @param cityCode the value for address_book.city_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.city_name
     *
     * @return the value of address_book.city_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.city_name
     *
     * @param cityName the value for address_book.city_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.district_code
     *
     * @return the value of address_book.district_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.district_code
     *
     * @param districtCode the value for address_book.district_code
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.district_name
     *
     * @return the value of address_book.district_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.district_name
     *
     * @param districtName the value for address_book.district_name
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.detail
     *
     * @return the value of address_book.detail
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.detail
     *
     * @param detail the value for address_book.detail
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.label
     *
     * @return the value of address_book.label
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.label
     *
     * @param label the value for address_book.label
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.is_default
     *
     * @return the value of address_book.is_default
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.is_default
     *
     * @param isDefault the value for address_book.is_default
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.create_time
     *
     * @return the value of address_book.create_time
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.create_time
     *
     * @param createTime the value for address_book.create_time
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.update_time
     *
     * @return the value of address_book.update_time
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.update_time
     *
     * @param updateTime the value for address_book.update_time
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.create_user
     *
     * @return the value of address_book.create_user
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.create_user
     *
     * @param createUser the value for address_book.create_user
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.update_user
     *
     * @return the value of address_book.update_user
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.update_user
     *
     * @param updateUser the value for address_book.update_user
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_book.is_deleted
     *
     * @return the value of address_book.is_deleted
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_book.is_deleted
     *
     * @param isDeleted the value for address_book.is_deleted
     *
     * @mbggenerated Wed Aug 24 23:43:13 CST 2022
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}