package com.ayz.reggie.pojo;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.type
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.sort
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.create_time
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.update_time
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.create_user
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.update_user
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private Long updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.type
     *
     * @return the value of category.type
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.type
     *
     * @param type the value for category.type
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.sort
     *
     * @return the value of category.sort
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.sort
     *
     * @param sort the value for category.sort
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.create_time
     *
     * @return the value of category.create_time
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.create_time
     *
     * @param createTime the value for category.create_time
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.update_time
     *
     * @return the value of category.update_time
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.update_time
     *
     * @param updateTime the value for category.update_time
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.create_user
     *
     * @return the value of category.create_user
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.create_user
     *
     * @param createUser the value for category.create_user
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.update_user
     *
     * @return the value of category.update_user
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.update_user
     *
     * @param updateUser the value for category.update_user
     *
     * @mbggenerated Mon Aug 22 22:57:17 CST 2022
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }
}