package com.ayz.reggie.pojo;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;

import java.io.Serializable;

public class DishFlavor implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.id
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.dish_id
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    private Long dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.name
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.value
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.create_time
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.update_time
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.create_user
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.update_user
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_flavor.is_deleted
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.id
     *
     * @return the value of dish_flavor.id
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.id
     *
     * @param id the value for dish_flavor.id
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.dish_id
     *
     * @return the value of dish_flavor.dish_id
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public Long getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.dish_id
     *
     * @param dishId the value for dish_flavor.dish_id
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setDishId(Long dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.name
     *
     * @return the value of dish_flavor.name
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.name
     *
     * @param name the value for dish_flavor.name
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.value
     *
     * @return the value of dish_flavor.value
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.value
     *
     * @param value the value for dish_flavor.value
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.create_time
     *
     * @return the value of dish_flavor.create_time
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.create_time
     *
     * @param createTime the value for dish_flavor.create_time
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.update_time
     *
     * @return the value of dish_flavor.update_time
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.update_time
     *
     * @param updateTime the value for dish_flavor.update_time
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.create_user
     *
     * @return the value of dish_flavor.create_user
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.create_user
     *
     * @param createUser the value for dish_flavor.create_user
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.update_user
     *
     * @return the value of dish_flavor.update_user
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.update_user
     *
     * @param updateUser the value for dish_flavor.update_user
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_flavor.is_deleted
     *
     * @return the value of dish_flavor.is_deleted
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_flavor.is_deleted
     *
     * @param isDeleted the value for dish_flavor.is_deleted
     *
     * @mbggenerated Tue Aug 23 19:54:41 CST 2022
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}