package com.ayz.reggie.pojo;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;

import java.io.Serializable;
import java.math.BigDecimal;

public class Dish implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.id
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.name
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.category_id
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.price
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.code
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.image
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.description
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.status
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.sort
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.create_time
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.update_time
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.create_user
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.update_user
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    @TableField(fill = FieldFill.UPDATE)
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.is_deleted
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.id
     *
     * @return the value of dish.id
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.id
     *
     * @param id the value for dish.id
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.name
     *
     * @return the value of dish.name
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.name
     *
     * @param name the value for dish.name
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.category_id
     *
     * @return the value of dish.category_id
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.category_id
     *
     * @param categoryId the value for dish.category_id
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.price
     *
     * @return the value of dish.price
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.price
     *
     * @param price the value for dish.price
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.code
     *
     * @return the value of dish.code
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.code
     *
     * @param code the value for dish.code
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.image
     *
     * @return the value of dish.image
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.image
     *
     * @param image the value for dish.image
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    @Override
    public String toString() {
        return "Dish{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", categoryId=" + categoryId +
                ", price=" + price +
                ", code='" + code + '\'' +
                ", image='" + image + '\'' +
                ", description='" + description + '\'' +
                ", status=" + status +
                ", sort=" + sort +
                ", createTime='" + createTime + '\'' +
                ", updateTime='" + updateTime + '\'' +
                ", createUser=" + createUser +
                ", updateUser=" + updateUser +
                ", isDeleted=" + isDeleted +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.description
     *
     * @return the value of dish.description
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.description
     *
     * @param description the value for dish.description
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.status
     *
     * @return the value of dish.status
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.status
     *
     * @param status the value for dish.status
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.sort
     *
     * @return the value of dish.sort
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.sort
     *
     * @param sort the value for dish.sort
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.create_time
     *
     * @return the value of dish.create_time
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.create_time
     *
     * @param createTime the value for dish.create_time
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.update_time
     *
     * @return the value of dish.update_time
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.update_time
     *
     * @param updateTime the value for dish.update_time
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.create_user
     *
     * @return the value of dish.create_user
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.create_user
     *
     * @param createUser the value for dish.create_user
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.update_user
     *
     * @return the value of dish.update_user
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.update_user
     *
     * @param updateUser the value for dish.update_user
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.is_deleted
     *
     * @return the value of dish.is_deleted
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.is_deleted
     *
     * @param isDeleted the value for dish.is_deleted
     *
     * @mbggenerated Mon Aug 22 23:49:55 CST 2022
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}