package com.ayz.reggie.pojo;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;

import java.math.BigDecimal;

public class ShoppingCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.name
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.image
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.dish_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private Long dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.setmeal_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private Long setmealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.dish_flavor
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private String dishFlavor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.number
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.amount
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.create_time
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    @TableField(fill = FieldFill.INSERT)
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.id
     *
     * @return the value of shopping_cart.id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.id
     *
     * @param id the value for shopping_cart.id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.name
     *
     * @return the value of shopping_cart.name
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.name
     *
     * @param name the value for shopping_cart.name
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.image
     *
     * @return the value of shopping_cart.image
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.image
     *
     * @param image the value for shopping_cart.image
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.dish_id
     *
     * @return the value of shopping_cart.dish_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public Long getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.dish_id
     *
     * @param dishId the value for shopping_cart.dish_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setDishId(Long dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.setmeal_id
     *
     * @return the value of shopping_cart.setmeal_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public Long getSetmealId() {
        return setmealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.setmeal_id
     *
     * @param setmealId the value for shopping_cart.setmeal_id
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setSetmealId(Long setmealId) {
        this.setmealId = setmealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.dish_flavor
     *
     * @return the value of shopping_cart.dish_flavor
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public String getDishFlavor() {
        return dishFlavor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.dish_flavor
     *
     * @param dishFlavor the value for shopping_cart.dish_flavor
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setDishFlavor(String dishFlavor) {
        this.dishFlavor = dishFlavor == null ? null : dishFlavor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.number
     *
     * @return the value of shopping_cart.number
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.number
     *
     * @param number the value for shopping_cart.number
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.amount
     *
     * @return the value of shopping_cart.amount
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.amount
     *
     * @param amount the value for shopping_cart.amount
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.create_time
     *
     * @return the value of shopping_cart.create_time
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.create_time
     *
     * @param createTime the value for shopping_cart.create_time
     *
     * @mbggenerated Thu Aug 25 11:53:31 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}